config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # verb 'path', to: 'controller#action'

  # READ all restaurants
  get "tasks", to: "tasks#index"

  # CREATE a restaurant
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  # READ one restaurant
  get 'tasks/:id', to: 'tasks#show', as: :task

  # UPDATE a restaurant
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task # GET the HTML form (pre-filled with restaurant attributes) for editing = 1 request
  patch 'tasks/:id', to: 'tasks#update' # PATCH the parameters to update an existing restaurant = 1 request

  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show; end

  def edit; end

  def update
    # @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%# <%= f.label :completed %>
  <%# <%= f.checkbox :completed %> 
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit a task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Edit', edit_task_path(@task) %>
<p><%= link_to 'Back to my tasks', tasks_path %></p>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title,
    task_path(task) %></li>
  <% end %>
</ul>
  <%= link_to "Add new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Add a new task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<%= link_to "Back to My tasks", tasks_path %>
<%= link_to "Edit my task", edit_task_path(@task) %>
<%= link_to "Delete", task_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are sure you?"}%>

<%# <p><%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
<%# <p><%= link_to 'Delete', restaurant_path(@restaurant), data: {turbo_method: :delete, turbo_confirm: "Are sure you?"} %>